version: '3.9'

services:
  backend:
    build:
      context: ./CharityShop.Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=charityshop;Username=postgres;Password=postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - charityshop-net  

  db:
    image: postgres:latest
    container_name: charityshop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: charityshop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - charityshop-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - charityshop-net
    depends_on:
      - db

volumes:
  db_data:

networks:
  charityshop-net:
    driver: bridge
